### ISSUE TITLE
BUG: Discovered By/Discovered ON not populated

### ISSUE THREAD

**Issue by celabgalactic** [mhebrard/nms-browser#17]
It appears the info sidebar is not populating Discovered BY for some systems.  This seems to occur rarely and is noticed to occur when the discovered ON date is not populated.  Example AGT Holbere .  More investigation will continue to see if other data produces similar results.

**Comment by mhebrard** [comment]
I was relaying on 'Discovery Date' to fill the discovery and survey...
Many time, the discovery date is actually unknown (In game display "3 years ago" but no precise date)... in that case, the discovered by info was not populated either...
v0.7.0 should fix that
