### ISSUE TITLE
Feature Request: Search for System on NAVI screen

### ISSUE THREAD

**Issue by celabgalactic** [mhebrard/nms-browser#18]
Suggestion: If user presses Q (for query), bring up a pop up query box to allow a user to type a system name to center the view on.  Ideally the search box could show a list of autocomplete suggestions but a basic search match box would suffice.  After pressing enter to search, the screen would shift to focus and select the required system OR display an error pop up message for no match.

**Comment by mhebrard** [comment]
I think the v0.8.0 address this request as the left menu allows user to search for galaxy, then region, then system.

Closing for now.
Don't hesitate to re-open if needed
